### ISSUE TITLE
Plan after ExoPlayer v2 is deprecated since 2024-04-03

### ISSUE THREAD

**Issue by paulisidore** [jepiqueau/capacitor-video-player#160]
Hello, ExoPlayer v2 is deprecated (https://github.com/google/ExoPlayer) do you have any plans to migrate to AndroidX Media3 as suggested by the ExoPlayer team? 

I ask this because on an Android device the plugin refuses to play the video due to an issue related to Google Cast.
Error trace on Android Studio:

```
java.lang.IllegalStateException: Failed to initialize CastContext.
at com.google.android.gms.cast.framework.CastContext.zzf(com.google.android.gms:play-services-cast-framework@@21.4.0:11)
at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@21.4.0:15)
at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.initializeCastService(FullscreenExoPlayerFragment.java:1266)
at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.onCreateView(FullscreenExoPlayerFragment.java:248)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
```

**Comment by paulisidore** [comment]
Finally I fixed the issue on Android, here are the changes made for those who will encounter the same problem as me.
I will make a push request later.

in **AndroidManifest.xml**: 
Add this line

```
<application 
...
...
<activity            
   ...
   ... 
   android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
  `android:supportsPictureInPicture="true">`

<meta-data
            android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
            android:value="your.package.id.CastOptionsProvider" />

```

Create new java Class in Android Studio in the same folder with MainActivity.java and named it **CastOptionsProvider.java** after copy and paste this code lines

```

package your.package.id; //replace with your package id

import android.content.Context;
import android.util.Log;

import androidx.annotation.NonNull;

import com.google.android.gms.cast.framework.CastOptions;
import com.google.android.gms.cast.framework.OptionsProvider;
import com.google.android.gms.cast.framework.SessionProvider;

import java.util.List;

public class CastOptionsProvider implements OptionsProvider {
  @Override
  public CastOptions getCastOptions(Context context) {
    Log.d("Capacitor", "getCastOptions: Package Name "+ context.getApplicationContext().getPackageName());
    CastOptions castOptions = new CastOptions.Builder()
      .setReceiverApplicationId(context.getPackageName())
      .build();
    return castOptions;
  }
  @Override
  public List<SessionProvider> getAdditionalSessionProviders(Context context) {
    return null;
  }

}
```

And in in the plugin file **FullscreenExoPlayerFragment.java** i do some correction: 

```
 public void onDestroy() {
    super.onDestroy();
    -if (chromecast) mRouter.removeCallback(mCallback);
    +if (chromecast) {
     + if (mRouter != null)
        +mRouter.removeCallback(mCallback);
   + };
 releasePlayer();
  }
...
...
public void onPause() {
    super.onPause();
   - if (chromecast) castContext.removeCastStateListener(castStateListener);
    +if (chromecast) {
      +if (castContext != null)
        +castContext.removeCastStateListener(castStateListener);
    +};
...
...
public void releasePlayer() {
    if (player != null) {
      playWhenReady = player.getPlayWhenReady();
      playbackPosition = player.getCurrentPosition();
      currentWindow = player.getCurrentWindowIndex();
      mediaSessionConnector.setPlayer(null);
      mediaSession.setActive(false);
      player.setRepeatMode(player.REPEAT_MODE_OFF);
      player.removeListener(listener);
      player.release();
      player = null;
      showSystemUI();
      resetVariables();
      if (chromecast) {
        -castPlayer.release();
        -castPlayer = null;
        +if (castPlayer != null){
          +castPlayer.release();
          +castPlayer = null;
        +}
      }
    }
  }

...
...

public void setMuted(boolean _isMuted) {
    isMuted = _isMuted;
   - if (isMuted) {
      -curVolume = player.getVolume();
     - player.setVolume(0L);
    -} else {
      -player.setVolume(curVolume);
   + if (player != null){
      +if (isMuted) {
        +curVolume = player.getVolume();
        +player.setVolume(0L);
      +} else {
        +player.setVolume(curVolume);
      +}
    }
  }

```

**Comment by paulisidore** [comment]
See PR #161

**Comment by paulisidore** [comment]
Since I was able to fix the issue on **Android with Capacitor 6 and ExoPlayer v2** in PR #161 , I think the question of migrating to Android Media 3 is premature at the moment. I leave it to the maintainer (@jepiqueau)  of the project to move forward according to his schedule. Thanks again for this plugin.

**Comment by jepiqueau** [comment]
@paulisidore the ownership of the plugin has been transfer to [harmonwood](https://github.com/harmonwood) today.
