### ISSUE TITLE
StringIndexOutOfBoundsException on initPlayer on android 

### ISSUE THREAD

**Issue by marfrede** [jepiqueau/capacitor-video-player#45]
android studio error message when initPlayer() is called:
```
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:521)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
     ...
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=4
        at java.lang.String.substring(String.java:2060)
        at com.jeep.plugin.capacitor.CapacitorVideoPlayer.getFilePath(CapacitorVideoPlayer.java:163)
        at com.jeep.plugin.capacitor.CapacitorVideoPlayer.initPlayer(CapacitorVideoPlayer.java:134)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        ...
```

my code:

```
import { Component, Input, OnInit } from '@angular/core';
import { Plugins } from '@capacitor/core';
import * as WebVPPlugin from 'capacitor-video-player';
import { CapacitorVideoPlayerPlugin } from 'capacitor-video-player';
const { CapacitorVideoPlayer, Device } = Plugins;

@Component({
  selector: 'app-video',
  templateUrl: './video.component.html',
  styleUrls: ['./video.component.scss'],
})
export class VideoComponent implements OnInit {

  @Input() src: string;
  private videoPlayer: CapacitorVideoPlayerPlugin;

  constructor() { }

  async ngOnInit() {
    // define the plugin to use
    const info = await Device.getInfo();
    if (info.platform === 'ios' || info.platform === 'android') {
      this.videoPlayer = CapacitorVideoPlayer;
    } else {
      this.videoPlayer = WebVPPlugin.CapacitorVideoPlayer;
    }
    // add listeners to the plugin
    // this._addListenersToPlayerPlugin();
  }

  public async play() {
    const res: any = await this.videoPlayer.initPlayer({
      mode: 'fullscreen',
      url: 'http://techslides.com/demos/sample-videos/small.mp4',
      playerId: 'fullscreen',
      componentTag: 'app-video'
    });
  }

}
```

**Comment by jepiqueau** [comment]
@marfrede 
remove line
```
import { CapacitorVideoPlayerPlugin } from 'capacitor-video-player';
```
replace line 
```
private videoPlayer: CapacitorVideoPlayerPlugin;
```
by 
```
private videoPlayer: any;
```
Tell me if it is not working
