### ISSUE TITLE
Compatibility with Capacitor 3

### ISSUE THREAD

**Issue by LuisManuel1983** [jepiqueau/capacitor-video-player#46]
Hi, I've been using this plugin with an app build on Ionic with Capacitor 2 and it works great, by far this is the best option I've found. However, I decided to migrate the app to capacitor 3 because it helps with various aspects of my app, so when doing the migration I also updated this plugin to version "3.0.0-rc.1" and when I try to play a video, it keeps crashing and I have no idea what is happening. My code is as follows:

**My imports**
_import { Capacitor } from '@capacitor/core';
import { CapacitorVideoPlayer } from 'capacitor-video-player';
import * as PluginsLibrary from 'capacitor-video-player';_

**And this is how I use it:**
![image](https://user-images.githubusercontent.com/16975334/122316362-bbe54a00-cee9-11eb-8128-ca0abf9a8d0b.png)

All I'm able to see in the console when I inspect my device is this:
![image](https://user-images.githubusercontent.com/16975334/122319023-02d53e80-ceee-11eb-89e8-1d5e03877aa1.png)

After that, the app closes on my Android phone (Xiaomi with android 10)

I saw in the documentation this:
`import { Capacitor } from '@capacitor/core';
import { CapacitorVideoPlayer } from 'capacitor-video-player';

export const setVideoPlayer = async (): Promise<any>=> {
  const platform = Capacitor.getPlatform();
  return {plugin:CapacitorVideoPlayer, platform};
};`

But I have no idea how I'm supposed to use that. Is this plugin compatible with capacitor 3? Any help is greatly appreciated

**Comment by jepiqueau** [comment]
@LuisManuel1983 yes it is compatible if you use the release 3.0.0-rc.1. Look at angular-videoplayer-app-starter tag 1.0.0-rc.1.

**Comment by jepiqueau** [comment]
@LuisManuel1983 
const player = await setVideoPlayer ()
this.videoPlayer = player.plugin
And after you do as before
this.videoPlayer. addListener('jeepCapVideoPlay',...)
this.videoPlayer.play () ...

**Comment by jepiqueau** [comment]
@LuisManuel1983 do not forget to delete from your app the android and iOS folder which are not compatible and do
npm run build
npx cap add android
npx cap add ios
npm run build
npx cap sync
npm run build
npx cap copy
npx cap open android
In Android Studio check that the gradles release is 7.0 otherwise set it up to 7.0 synchronize the project with gradle and build your app it should work.

**Comment by LuisManuel1983** [comment]
Hi, thanks for the quick reply! sorry, I didn't realize you had made a demo for capacitor 3, because the readme is pointing [here ](https://github.com/jepiqueau/angular-videoplayer-app-starter/tree/0.6.3) but the version with cap 3 is [here](https://github.com/jepiqueau/angular-videoplayer-app-starter)

I'll start working today and tomorrow probably will update after tests are succesful

Thanks again

**Comment by LuisManuel1983** [comment]
Ok I did everything you mention @jepiqueau including deleting the android folder (ios I don't manage in this computer) and the www folder, the steps to build and compile... and I keep getting the same error. This is my console when inspecting android device:

![image](https://user-images.githubusercontent.com/16975334/122498575-5bbfd800-cfbd-11eb-8d41-dcecf8553861.png)

The behavior that I see is that the app crashes completely, it closes instanly. When I test it on the web browser (via ionic serve) it works well. The problem is when testing on android

The relevant part of my current code is this:
![image](https://user-images.githubusercontent.com/16975334/122498486-37fc9200-cfbd-11eb-8edc-e5a434e4e9bb.png)

![image](https://user-images.githubusercontent.com/16975334/122498802-bf4a0580-cfbd-11eb-8645-c0ca57e42edf.png)

The function "addListenersToPlayerPlugin" and related methods I just copied exactly from your angular demo... so I don't know, maybe is something related to ionic?

**Comment by jepiqueau** [comment]
@LuisManuel1983 can you check in AndroidStudio file->project structure that android gradle plug-in is 4.4.1 and gradle version 7.0. Did you test the angular-videoplayer-app-starter as for me it works

**Comment by LuisManuel1983** [comment]
Hi, yes, I checked the gradle version, is 7.0, also I did test the angular-videoplayer-app-starter and works locally, but then again, when I test my own ionic app it also works locally, the problem is when I test the apk in Android

**Comment by LuisManuel1983** [comment]
Hi, I made a repo using your plugin with a new App that has ionic and capacitor 3:

[https://github.com/LuisManuel1983/ionic-video-demo](https://github.com/LuisManuel1983/ionic-video-demo)

When I test on local computer (web browser) using "ionic serve" all works well:
![image](https://user-images.githubusercontent.com/16975334/122658434-42449a80-d13b-11eb-9e4f-d67cbd2e3284.png)

But when I tested on android, it crashes and this is everything I can see in the console:
![image](https://user-images.githubusercontent.com/16975334/122658443-5ee0d280-d13b-11eb-9b46-0fd4a465f318.png)

Could you please take a look at my repo and see what I'm doing wrong? Is a really simple demo, I think I followed every step you mentioned but maybe I miss something

**Comment by jepiqueau** [comment]
@LuisManuel1983 did you test it on Android device simulator which one or on a real device the image you gave me for the error is a chrome image not the console from androidstudio

**Comment by jepiqueau** [comment]
@LuisManuel1983 I look at your example it works on the browser as the browser accepts embedded videos which is not the case of Android and iOS. your HTML file should be different for browser and native Look carefully at the `angular-videoplayer-app-starter` and modify your code for NATIVE only FULLSCREEN mode is available. hope this help.

**Comment by LuisManuel1983** [comment]
> @LuisManuel1983 did you test it on Android device simulator which one or on a real device the image you gave me for the error is a chrome image not the console from androidstudio

I tested on a real device (Redmi note 9s with android 11), what I'm doing is I install the apk directly to my phone and connect via usb to my computer, then I inspect via chrome dev console, I then to not test on android simulator and just go directly to a real device, but I will try that to see if something else shows up

**Comment by LuisManuel1983** [comment]
> @LuisManuel1983 I look at your example it works on the browser as the browser accepts embedded videos which is not the case of Android and iOS. your HTML file should be different for browser and native Look carefully at the `angular-videoplayer-app-starter` and modify your code for NATIVE only FULLSCREEN mode is available. hope this help.

My app is not supposed to be for web, is for android/ios only, so I never set up different files for web and native, given that this app is intended for native only. Regarding the mode, I have NEVER used "embeed" mode, always fullscreen:

![image](https://user-images.githubusercontent.com/16975334/122679133-b1f86b00-d1b7-11eb-8d51-116f383c747f.png)

![image](https://user-images.githubusercontent.com/16975334/122679155-c9cfef00-d1b7-11eb-9217-e882425d9755.png)

I review again the code from `angular-videoplayer-app-starter` and I followed the logic to see if there's something different for Android platform but I can't see much difference from your code to the example I put:
![image](https://user-images.githubusercontent.com/16975334/122679546-4ca57980-d1b9-11eb-89d2-49467fb60eff.png)

![image](https://user-images.githubusercontent.com/16975334/122680107-b4f55a80-d1bb-11eb-935f-402de259aa06.png)

Is it because I'm not using subtitle and laguage options? Anyway, I'll try using the android simulator and see if something else pop ups

**Comment by LuisManuel1983** [comment]
All right, I tested on android simulator, same error, I cleaned the console just before clicking the image to play the video, and this is the stack trace:

![image](https://user-images.githubusercontent.com/16975334/122680885-8aa59c00-d1bf-11eb-971c-7516e8a19948.png)

### **Complete trace:**

2021-06-20 12:00:40.623 8714-8714/io.ionic.starter I/Capacitor/Console: File: http://localhost/src_app_video1_video1_module_ts.js - Line 591 - Msg: PLAY video 1
2021-06-20 12:00:40.629 8714-8880/io.ionic.starter V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 75694358, pluginId: CapacitorVideoPlayer, methodName: initPlayer
2021-06-20 12:00:40.629 8714-8880/io.ionic.starter V/Capacitor: callback: 75694358, pluginId: CapacitorVideoPlayer, methodName: initPlayer, methodData: {"mode":"fullscreen","url":"https:\/\/raw.githubusercontent.com\/jepiqueau\/jeep\/master\/assets\/videos\/Bike720.mp4","playerId":"fullscreen","componentTag":"app-video1"}
2021-06-20 12:00:40.632 8714-8825/io.ionic.starter D/CapacitorVideoPlayer: **** isTV false ****
2021-06-20 12:00:40.637 8714-8825/io.ionic.starter V/CapacitorVideoPlayer: display url: https://raw.githubusercontent.com/jepiqueau/jeep/master/assets/videos/Bike720.mp4
2021-06-20 12:00:40.637 8714-8825/io.ionic.starter V/CapacitorVideoPlayer: display subtitle: 
2021-06-20 12:00:40.637 8714-8825/io.ionic.starter V/CapacitorVideoPlayer: display language: 
2021-06-20 12:00:40.638 8714-8825/io.ionic.starter E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=4
        at java.lang.String.substring(String.java:2060)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.Utilities.FilesUtils.getFilePath(FilesUtils.java:16)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.CapacitorVideoPlayerPlugin.initPlayer(CapacitorVideoPlayerPlugin.java:118)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    
    
    --------- beginning of crash
2021-06-20 12:00:40.645 8714-8825/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: io.ionic.starter, PID: 8714
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:593)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=4
        at java.lang.String.substring(String.java:2060)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.Utilities.FilesUtils.getFilePath(FilesUtils.java:16)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.CapacitorVideoPlayerPlugin.initPlayer(CapacitorVideoPlayerPlugin.java:118)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    
    
    --------- beginning of system
2021-06-20 12:00:40.787 8714-8714/io.ionic.starter D/Capacitor: App paused
2021-06-20 12:00:40.859 8714-8825/io.ionic.starter I/Process: Sending signal. PID: 8714 SIG: 9

**Comment by LuisManuel1983** [comment]
Ok I finally solved it and the solution couldn't be more simple, just add the variables (declared with null values) for subtitle, language and subtitle options:

![image](https://user-images.githubusercontent.com/16975334/122704433-ba858b80-d221-11eb-8b28-455320c02f7a.png)

I came to this after analize the log from my error and see this line of code in the plugin:
![image](https://user-images.githubusercontent.com/16975334/122704671-223bd680-d222-11eb-850c-6eee5b94b869.png)

The problem is that "subtitle" can never be null because how it's declared, so, if I DON'T send it, then the plugin will throw an exception when the method "getFilePath" is called to process an empty string (you can see in the logs I put the main exception being **_"Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=4"_** )
![image](https://user-images.githubusercontent.com/16975334/122704918-a8f0b380-d222-11eb-9fef-fad1a69b26c5.png)

So even thought my app is now working well, may I suggest some fix? I've never developed a plugin for Ionic and/or Angular so this is just my opinion, because I'm not sure if for language and subtitleOptions, a similar fix is needed. I'll leave this issue open for you to decide how to handle it

**Comment by jepiqueau** [comment]
@LuisManuel1983 I am pleased that you find what causing the error.I will fix this in the next release. It is my vacation time so it was hard to answer you just with my phone device. The test should be subtitle!=null or subtitle.length > 0

**Comment by jepiqueau** [comment]
@LuisManuel1983 this has been fixed in 3.0.0-rc.2. Thanks for your help in debugging.

**Comment by LuisManuel1983** [comment]
No, thanks to you, this plugin is really awesome, sorry to have bother you during vacation time
