### ISSUE TITLE
Video player error on Android devices

### ISSUE THREAD

**Issue by mzimnikoval** [jepiqueau/capacitor-video-player#91]
Hello, we facing issues when we trying to run video stream on Android phones. When we try livestream url in format .m3u it throws this error

`E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
`

And when we changes file format to .mpd ti works but after some time it starts buffering and player throw this error

`E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.dash.DefaultDashChunkSource.getNextChunk(DefaultDashChunkSource.java:349)
        at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.continueLoading(ChunkSampleStream.java:524)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.dash.DashMediaPeriod.continueLoading(DashMediaPeriod.java:297)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:205)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1760)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1739)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:241)
        at android.os.HandlerThread.run(HandlerThread.java:67)`

Thank you for help

**Comment by jepiqueau** [comment]
@mzimnikoval can you provide the link of your livestream url

**Comment by mzimnikoval** [comment]
One is http://92.62.234.206/slagr.m3u

and the other one for android is https://arenasportslovakia.ddns.net:443/dashLive1/slager.mpd

**Comment by jepiqueau** [comment]
@mzimnikoval  [https://arenasportslovakia.ddns.net:443/dashLive1/slager.mpd](https://arenasportslovakia.ddns.net/dashLive1/slager.mpd) is working fine on android.

**Comment by jepiqueau** [comment]
@mzimnikoval in `angular-videoplayer-app-starter` home page i replaced `private mpd = 'https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd';` by `private mpd ='https://arenasportslovakia.ddns.net:443/dashLive1/slager.mpd';`
.m3u playlist are not supported by Exoplayer only HSL .m3u8
hope this clarify

**Comment by mzimnikoval** [comment]
Hi, @jepiqueau we are using vue app and when I drop it to the json list, that mpd stream starting buffering, and after some time it crashes, only on android though
